controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

# 안전성이 강화된 Joint Trajectory Controller 설정
joint_trajectory_controller:
  ros__parameters:
    joints:
      - link1_1_joint
      - link2_1_joint
      - link3_1_joint
      - link4_1_joint
      - link5_1_joint
      - link6_1_joint
    
    command_interfaces:
      - position
    state_interfaces:
      - position
    
    # 안전성 강화 설정
    constraints:
      goal_time: 2.0  # 목표 도달 시간 여유
      stopped_velocity_tolerance: 0.05  # 정지 속도 허용 오차
      
      # 각 관절별 제약 조건 설정
      link1_1_joint:
        trajectory: 0.2   # 궤적 추종 오차 허용범위 (rad)
        goal: 0.1         # 목표 위치 오차 허용범위 (rad)
        
      link2_1_joint:
        trajectory: 0.15  # 2번 관절은 더 엄격하게 (상하 움직임)
        goal: 0.08
        
      link3_1_joint:
        trajectory: 0.2
        goal: 0.1
        
      link4_1_joint:
        trajectory: 0.2
        goal: 0.1
        
      link5_1_joint:
        trajectory: 0.2
        goal: 0.1
        
      link6_1_joint:
        trajectory: 0.2
        goal: 0.1
    
    # 안전 기능 활성화
    state_publish_rate: 100  # 상태 발행 빈도 증가
    action_monitor_rate: 50.0
    allow_partial_joints_goal: false  # 부분 목표 비허용
    open_loop_control: false  # 피드백 제어 사용
    
    # 궤적 보간 설정
    allow_integration_in_goal_trajectories: true

# Forward Position Controller (Emergency용)
forward_position_controller:
  ros__parameters:
    joints:
      - link1_1_joint
      - link2_1_joint
      - link3_1_joint
      - link4_1_joint
      - link5_1_joint
      - link6_1_joint
    interface_name: position
    command_interfaces:
      - position

# Joint State Broadcaster
joint_state_broadcaster:
  ros__parameters:
    joints:
      - link1_1_joint
      - link2_1_joint
      - link3_1_joint
      - link4_1_joint
      - link5_1_joint
      - link6_1_joint
    
    # 상태 발행 빈도 증가 (모니터링 개선)
    publish_rate: 100.0