controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    cartesian_controller:
      type: cartesian_controllers/CartesianController


cartesian_controller:
  ros__parameters:
    robot_description_parameter: robot_description
    base_link: base_link  # 로봇 베이스 링크 이름
    end_effector_link: tool0  # 엔드 이펙터 링크 이름
    joints:  # 제어할 관절 목록
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:  # 명령 인터페이스 유형
      - position
    state_interfaces:  # 상태 인터페이스 유형
      - position
    use_velocity_commands: false  # true: 트위스트 명령 사용, false: 포즈 명령 사용
    position_tolerance: 0.001  # 위치 허용 오차 (미터)
    orientation_tolerance: 0.01  # 방향 허용 오차 (라디안)
    control_rate: 100.0  # 제어 주기 (Hz)
    max_velocity: 0.5  # 최대 속도 (미터/초)